Docker credentials resource is added.
duplocloud/terraform-provider-duplocloud pull request #11
Opened 2021-09-21 18:37 UTC by tahir-duplo

- Docker credentials resource is added.
- Delete is implemented using update API by making all fields empty, We don't have a delete API.
- DNS name is added in Duplo alb resource.
- 90 seconds wait added for elasticache delete.
- availability_zones added for the plan data source.

2021-09-23 19:39 UTC, joek-duplo requested changes

2021-09-23 19:39 UTC, joek-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew: true,
we should not `ForceNew` here.

2021-09-23 19:39 UTC, joek-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew:  true,
we should not `ForceNew` here.

2021-09-23 19:39 UTC, joek-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew: true,
we should not `ForceNew` here.

2021-09-23 19:39 UTC, joek-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			Type:     schema.TypeString,
we should also have `Computed = true` here

2021-09-23 19:50 UTC, tahir-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			Type:     schema.TypeString,
done

2021-09-23 19:50 UTC, tahir-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew: true,
done

2021-09-23 19:50 UTC, tahir-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew:  true,
done

2021-09-23 19:50 UTC, tahir-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			ForceNew: true,
done

2021-09-24 17:15 UTC, joek-duplo approved these changes

2021-09-24 17:16 UTC, joek-duplo requested changes

2021-09-24 17:16 UTC, joek-duplo commented on duplocloud/resource_duplo_docker_credentials.go
> +			Type:     schema.TypeString,
@tahir-duplo  - it looks like `Computed: true` is still missing?

2021-09-24 17:18 UTC, joek-duplo approved these changes

2021-09-24 17:18 UTC, merged