Attribute `cors_allowed_host_names` added for cloudfront resource.
duplocloud/terraform-provider-duplocloud pull request #114
Opened 2022-07-12 14:18 UTC by tahir-duplo

Attribute `cors_allowed_host_names` added for cloudfront resource.

2022-07-12 14:18 UTC, zafarabbas commented
Task linked: [DUPLO-4333 Add CORS allowed host support in cloudfront distribution.](https://app.clickup.com/t/8655600/DUPLO-4333)

2022-07-12 16:28 UTC, joek-duplo requested changes

2022-07-12 16:28 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +	// d.Set("cors_allowed_host_names", flattenStringList("No Data From Backend"))
@tahir-duplo  - This commented-out line seems to have been the only place where we will have read this setting from the backend.  If we do not read the setting from a backend, I think we may have an issue with this code.

2022-07-12 16:28 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		Id:                   cfdId,
@tahir-duplo  - does this work when the user does not specify any value?  In other words, does `expandStringList` handle getting an empty list?  Second question:  can `d.Get("cors_allowed_host_names")` return `nil`?  if so, we will get a panic at runtime.

2022-07-12 16:33 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +	// d.Set("cors_allowed_host_names", flattenStringList("No Data From Backend"))
Backend just expect CORS host names on create API but does not return this data as part of get API

2022-07-12 16:33 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		CorsAllowedHostNames: expandStringList(d.Get("cors_allowed_host_names").([]interface{})),
Yes it work, it returns empty list.

2022-07-12 16:33 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		Id:                   cfdId,
Yes, it works, it returns an empty list.

2022-07-14 14:04 UTC, joek-duplo approved these changes

2022-07-14 14:04 UTC, merged