Duplo 4746 : Support for k8s ingress resource.
duplocloud/terraform-provider-duplocloud pull request #131
Opened 2022-08-24 21:48 UTC by tahir-duplo

- `duplocloud_k8_ingress`  resource added.

2022-08-24 21:48 UTC, zafarabbas commented
Task linked: [DUPLO-4746 TF provider support for ingress resources](https://app.clickup.com/t/8655600/DUPLO-4746)

2022-08-25 15:06 UTC, joek-duplo requested changes

2022-08-25 15:06 UTC, joek-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +	rp, err := c.DuploK8sIngressGet(tenantID, name)
I think we should also handle 404 - all v3 methods are supposed to return 404 when the resource does not exist.  we are also updating the backend to do that.

2022-08-25 15:06 UTC, joek-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +		if err != nil {
I think we should also handle 404 - all v3 methods are supposed to return 404 when the resource does not exist. we are also updating the backend to do that.

2022-08-25 15:06 UTC, joek-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +	d.Set("rule", []interface{}{flattenK8sIngressRules(duplo.Rules)})
I think this is an extra array wrapping an array.  since the method already returns an array.

2022-08-25 16:39 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +	rp, err := c.DuploK8sIngressGet(tenantID, name)
Done

2022-08-25 16:39 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +		if err != nil {
Done

2022-08-25 16:42 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8_ingress.go
> +	d.Set("rule", []interface{}{flattenK8sIngressRules(duplo.Rules)})
Done

2022-08-26 01:09 UTC, joek-duplo approved these changes

2022-08-26 05:02 UTC, merged