DUPLO-7960 and DUPLO-8317 fixed.
duplocloud/terraform-provider-duplocloud pull request #228
Opened 2023-03-20 18:45 UTC by tahir-duplo

- TF: support for NLB with Custom CIDRs
- New resource `duplocloud_aws_sqs_queue_v2` added.
- Azure VM avoiding re-creation changes done.

2023-03-20 18:45 UTC, zafarabbas commented
Task linked: [DUPLO-7960 TF: support for sqs standard/fifo for retention and visibility](https://app.clickup.com/t/8655600/DUPLO-7960)

2023-03-20 18:45 UTC, zafarabbas commented
Task linked: [DUPLO-8317 TF: support for NLB with Custom CIDRs](https://app.clickup.com/t/8655600/DUPLO-8317)

2023-03-21 00:21 UTC, joek-duplo requested changes
I don't want to create an `sqs_v2` resource.

Let's discuss on a call.  Also, see here: https://duplocloud.slack.com/archives/C03TX2CT1L3/p1679358062082149

2023-03-21 22:09 UTC, joek-duplo approved these changes

2023-03-23 10:42 UTC, merged