DUPLO-8848 - using new v3 rds api
duplocloud/terraform-provider-duplocloud pull request #243
Opened 2023-04-14 17:52 UTC by pravin-duplocloud

DUPLO-8848 - update rds v3 api. refactoring and cleanup be. use new v3 api  in ui/tf

2023-04-14 17:52 UTC, zafarabbas commented
Task linked: [DUPLO-8848 update TF to use newer RDS routes](https://app.clickup.com/t/8655600/DUPLO-8848)

2023-04-26 15:09 UTC, joek-duplo requested changes

2023-04-26 15:09 UTC, joek-duplo commented on docs/resources/rds_instance.md
> +terraform import duplocloud_rds_instance.mydb v3/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on docs/resources/rds_read_replica.md
> +terraform import duplocloud_rds_read_replica.read_replica v3/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on duplocloud/resource_duplo_rds_instance.go
> +	d.SetId(fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", duplo.TenantID, duplo.Name))
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on duplocloud/resource_duplo_rds_instance.go
> +	id := fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", tenantID, duplo.Name)
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on duplocloud/resource_duplo_rds_read_replica.go
> +	d.SetId(fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", duplo.TenantID, duplo.Name))
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on duplocloud/resource_duplo_rds_read_replica.go
> +	id := fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", tenantID, duplo.Name)
revert this change

2023-04-26 15:09 UTC, joek-duplo commented on examples/resources/duplocloud_rds_instance/import.sh
> -terraform import duplocloud_rds_instance.mydb v2/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
revert this change

2023-04-26 21:05 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_read_replica.go
> +	id := fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", tenantID, duplo.Name)
done

2023-04-26 21:05 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_read_replica.go
> +	d.SetId(fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", duplo.TenantID, duplo.Name))
done

2023-04-26 21:05 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_instance.go
> +	id := fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", tenantID, duplo.Name)
done

2023-04-26 21:05 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_instance.go
> +	d.SetId(fmt.Sprintf("v3/subscriptions/%s/RDSDBInstance/%s", duplo.TenantID, duplo.Name))
done

2023-04-26 21:05 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +terraform import duplocloud_rds_instance.mydb v3/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
done

2023-05-02 03:34 UTC, pravin-duplocloud commented on docs/resources/rds_read_replica.md
> +terraform import duplocloud_rds_read_replica.read_replica v3/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
done

2023-05-02 03:34 UTC, pravin-duplocloud commented on examples/resources/duplocloud_rds_instance/import.sh
> -terraform import duplocloud_rds_instance.mydb v2/subscriptions/*TENANT_ID*/RDSDBInstance/*SHORTNAME*
done

2023-05-02 03:35 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_read_replica.go
> +	d.SetId(fmt.Sprintf("v3/subscriptions/%s/aws/rds/instance/%s", duplo.TenantID, duplo.Name))
done

2023-06-26 16:54 UTC, joek-duplo approved these changes

2023-08-25 01:11 UTC, joek-duplo requested changes
still some bugs left

2023-08-25 01:11 UTC, joek-duplo commented on duplosdk/rds_instance.go
> +	idParts := strings.Split(id, "/")
revert this, the ID is not changing

2023-08-25 01:11 UTC, joek-duplo commented on duplosdk/rds_instance.go
> +	name := idParts[len(idParts)-1]
revert this the ID is not changing

2023-08-25 01:11 UTC, joek-duplo commented on duplosdk/rds_instance.go
> +	idParts := strings.Split(id, "/")
revert this, the ID is not changing

2023-08-25 01:11 UTC, joek-duplo commented on duplosdk/rds_instance.go
> +	name := idParts[len(idParts)-1] // use new v3 api ..take last one
revert this, the ID is not changing

2023-09-08 18:12 UTC, pravin-duplocloud commented on duplosdk/rds_instance.go
> +	idParts := strings.Split(id, "/")
done

2023-09-08 18:12 UTC, pravin-duplocloud commented on duplosdk/rds_instance.go
> +	name := idParts[len(idParts)-1]
done

2023-09-08 18:12 UTC, pravin-duplocloud commented on duplosdk/rds_instance.go
> +	idParts := strings.Split(id, "/")
done

2023-09-08 18:12 UTC, pravin-duplocloud commented on duplosdk/rds_instance.go
> +	name := idParts[len(idParts)-1] // use new v3 api ..take last one
done

2023-09-08 19:02 UTC, joek-duplo approved these changes
please have QA test before merging

2023-09-11 22:49 UTC, merged