DUPLO-9210 neglect tags created at backend new DUBPLO_CUSTOM_TAGS
duplocloud/terraform-provider-duplocloud pull request #253
Opened 2023-05-12 23:17 UTC by pravin-duplocloud

DUPLO-9210, DUPLO-9337, DUPLO-9336 - time stream tags

2023-05-12 23:17 UTC, zafarabbas commented
Task linked: [DUPLO-9337 Timestream TF: Updating tags gives table already exists error](https://app.clickup.com/t/8655600/DUPLO-9337)

2023-05-12 23:17 UTC, zafarabbas commented
Task linked: [DUPLO-9210 Timestream: aws tag manager support tags for timestream tables](https://app.clickup.com/t/8655600/DUPLO-9210)

2023-05-12 23:17 UTC, zafarabbas commented
Task linked: [DUPLO-9336 Timestream UI: Added tags should be shown in db/table json details](https://app.clickup.com/t/8655600/DUPLO-9336)

2023-05-12 23:17 UTC, zafarabbas commented
Task linked: [DUPLO-7734 Provided Tags are not attached to Timestream DB and Table](https://app.clickup.com/t/8655600/DUPLO-7734)

2023-05-19 16:25 UTC, joek-duplo requested changes
let's not do this - instead solve as we have discussed in the scrum

2023-06-20 19:22 UTC, joek-duplo requested changes

2023-06-20 19:22 UTC, joek-duplo commented on duplosdk/aws_timestream_database.go
> +	//rp.TenantID = tenantID
why is this code commented out?

2023-06-20 19:22 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_timestreamwrite_table.go
> +func getChangesTimestreamTags(all *[]duplosdk.DuploKeyStringValue, d *schema.ResourceData) (newTags *[]duplosdk.DuploKeyStringValue, deletedKeys []string) {
why do we have a completely new method for this instead of using the existing method?  I am against copy/pasting code instead making code re-usable

2023-06-26 17:01 UTC, pravin-duplocloud commented on duplosdk/aws_timestream_database.go
> +	//rp.TenantID = tenantID
not used as its already coming as argument.
done reverted

2023-06-27 15:48 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_aws_timestreamwrite_table.go
> +func getChangesTimestreamTags(all *[]duplosdk.DuploKeyStringValue, d *schema.ResourceData) (newTags *[]duplosdk.DuploKeyStringValue, deletedKeys []string) {
done. 
avoiding changes to other objects to avoid regression. 
no generic with *[]duplosdk.DuploKeyStringValue for state management

2023-07-21 15:56 UTC, joek-duplo requested changes
same comment:  it looks like we wrote a new method to deal with this logic instead of leveraging existing logic

2023-07-21 19:54 UTC, pravin-duplocloud commented
> same comment: it looks like we wrote a new method to deal with this logic instead of leveraging existing logic

as talked in today's call,  split method into smaller  ones.

2023-07-27 17:11 UTC, joek-duplo approved these changes

2023-09-08 17:38 UTC, joek-duplo requested changes
@pravin-duplocloud  - can you make the changes  we discussed in DM with @zafarabbas  and I.  please ensure that TF does not call a list API when it is reading a single element.

2023-09-08 19:01 UTC, joek-duplo approved these changes
please have QA test before merging

2023-09-15 02:57 UTC, merged