Duplo 5965
duplocloud/terraform-provider-duplocloud pull request #268
Opened 2023-06-29 14:16 UTC by michalpleszkun

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-06-29 14:16 UTC, zafarabbas commented
Task linked: [DUPLO-5965 Lambdas need the ability to have ephemeral storage: Add APIs to TF](https://app.clickup.com/t/8655600/DUPLO-5965)

2023-06-29 14:25 UTC, joek-duplo requested changes
we also forgot to set up ephemeral storage in the Update method

2023-06-29 14:25 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_lambda_function.go
> +	d.Set("ephemeral_storage", duplo.EphemeralStorage.Size)
`duplo.EphemeralStorage` can be `nil` but we aren't checking for it here.

2023-08-31 19:47 UTC, ddiaz-duplo commented
Could use some help testing this. I was using the example that @michalpleszkun added but I get the following error `Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist."`

```terraform
resource "duplocloud_s3_bucket" "s3bucket" {
  tenant_id = var.tenant_id
  name      = "miketest"
}

resource "duplocloud_aws_lambda_function" "test" {
  tenant_id         = var.tenant_id
  name              = "miketest"
  package_type      = "Zip"
  description       = "miketest lambda"
  s3_bucket         = duplocloud_s3_bucket.s3bucket.fullname
  s3_key            = "file.zip"
  memory_size       = 128
  runtime           = "python3.9"
  handler           = "main"
  ephemeral_storage = 1024
}
```
how do I retrieve that key?

2023-09-05 16:09 UTC, joek-duplo approved these changes

2023-09-05 16:09 UTC, merged