DUPLO-11315 mwaa sample doc
duplocloud/terraform-provider-duplocloud pull request #298
Opened 2023-09-06 23:22 UTC by pravin-duplocloud

mwaa sample doc

2023-09-06 23:22 UTC, zafarabbas commented
Task linked: [DUPLO-11315 [TF Doc] update airflow with examples](https://app.clickup.com/t/8655600/DUPLO-11315)

2023-09-08 17:30 UTC, joek-duplo approved these changes

2023-09-08 17:33 UTC, joek-duplo requested changes
@pravin-duplocloud - you cannot edit generated markdown, or it will just simply be overwritten the next time docs are generated.

done.
used
make doc

2023-09-08 18:06 UTC, joek-duplo approved these changes

2023-09-08 18:06 UTC, merged