DUPLO-9053 enable updating instance size and logging
duplocloud/terraform-provider-duplocloud pull request #300
Opened 2023-09-13 19:04 UTC by ddiaz-duplo

## Change description

User can now update `enable_logging` and `size` fields without destroying and recreating the rds instance

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)
## Tests

Tested on Test19.Duplocloud.net
```sh
Terraform will perform the following actions:

  # duplocloud_rds_instance.mydb will be updated in-place
  ~ resource "duplocloud_rds_instance" "mydb" {
      + deletion_protection = false
      ~ enable_logging      = false -> true
        id                  = "v2/subscriptions/81386040-9a07-4e76-a195-94191d9d47aa/RDSDBInstance/mydb"
        name                = "mydb"
      ~ size                = "db.t3.medium" -> "db.t4g.micro"
        # (15 unchanged attributes hidden)

      - timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-09-13 19:04 UTC, zafarabbas commented
Task linked: [DUPLO-9053 TF Provider: update RDS Instance size and reapplying again should not delete and recreate rds](https://app.clickup.com/t/8655600/DUPLO-9053)

2023-09-13 19:07 UTC, joek-duplo requested changes

2023-09-13 19:07 UTC, joek-duplo commented on duplosdk/rds_instance.go
> +		fmt.Sprintf("v3/subscriptions/%s/aws/rds/instance", tenantID),
this looks wrong, pretty sure there is a diff endpoint here.  can you check with @pravin-duplocloud  if you can't find it?

2023-09-14 13:42 UTC, ddiaz-duplo commented on duplosdk/rds_instance.go
> +		fmt.Sprintf("v3/subscriptions/%s/aws/rds/instance", tenantID),
Oops, I forgot to revert this.

2023-09-14 13:58 UTC, merged