Duplo 11472
duplocloud/terraform-provider-duplocloud pull request #302
Opened 2023-09-15 19:49 UTC by ddiaz-duplo

## Change description

Add examples for Infrastructure settings and lambda permissions

For some reason
```sh
make doc
``` 
isn't generating the documentation for lambda permissions.

## Related issues

https://app.clickup.com/t/8655600/DUPLO-11171
https://app.clickup.com/t/8655600/DUPLO-11472

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-09-15 19:49 UTC, zafarabbas commented
Task linked: [DUPLO-11472 TF: Doc:Example for infrastructure setting](https://app.clickup.com/t/8655600/DUPLO-11472)

2023-09-15 19:49 UTC, zafarabbas commented
Task linked: [DUPLO-11171 TF: Add example usage for `duplocloud_aws_lambda_permission` resource](https://app.clickup.com/t/8655600/DUPLO-11171)

2023-09-15 20:31 UTC, joek-duplo requested changes

2023-09-15 20:31 UTC, joek-duplo commented on examples/resources/duplocloud_aws_lambda_permissions/resource.tf
> +resource "aws_lambda_permission" "permission" {
this is not an example of duplo lambda permissions, it is an example of AWS's lambda permission. what are we trying to accomplish here?

2023-09-15 20:31 UTC, joek-duplo commented on examples/resources/duplocloud_infrastructure_setting/resource.tf
> +resource "duplocloud_infrastructure_setting" "settings" {
this example is way too complicated for most of our users.  please remove the:
 - dynamic block
 - lifecycle block
 - typed variable
 
instead, just show how to use this TF resource itself

2023-09-18 15:28 UTC, ddiaz-duplo commented on examples/resources/duplocloud_aws_lambda_permissions/resource.tf
> +resource "aws_lambda_permission" "permission" {
Good catch! thats why `make doc` wasn't working.

2023-09-18 16:10 UTC, joek-duplo requested changes

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_infrastructure_setting/resource.tf
> +resource "duplocloud_infrastructure_setting" "settings" {
docs for this resource are now useless, right?  we need proper docs

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_infrastructure_setting/resource.tf
> +  EnableSecretCsiDriver = "true"
this is incorrect

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_infrastructure_setting/resource.tf
> +  EnableAWSEfsVolumes   = "true"
this is incorrect

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_aws_lambda_permissions/import.sh
> +# Example: Importing an existing AWS lambda function permissions
this file is ineffective

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_aws_lambda_permissions/resource.tf
> +resource "duplocloud_aws_lambda_permission" "permission" {
this file is ineffective

2023-09-18 16:10 UTC, joek-duplo commented on examples/resources/duplocloud_infrastructure_setting/import.sh
> +terraform import duplocloud_infrastructure_setting.settings adminproxy/GetInfrastructureConfig/*NAME*
this is incorrect

2023-09-18 16:10 UTC, joek-duplo commented on duplosdk/aws_lambda_function.go
> +	var rp []DuploLambdaPermissionStatement
revert this change

2023-09-20 19:26 UTC, joek-duplo approved these changes

2023-09-20 19:26 UTC, merged