wip
duplocloud/terraform-provider-duplocloud pull request #304
Opened 2023-09-18 16:52 UTC by ddiaz-duplo

## Change description

Add support for `imageConfig` 

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-09-18 16:52 UTC, zafarabbas commented
Task linked: [DUPLO-11338 TF: support for Image configurations in Lambda](https://app.clickup.com/t/8655600/DUPLO-11338)

2023-09-19 20:30 UTC, joek-duplo reviewed
this looks good so far to me. :+1:

2023-09-22 17:28 UTC, joek-duplo requested changes

2023-09-22 20:12 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_aws_lambda_function.go
> +		ImageConfig:  d.Get("image_config").(*duplosdk.DuploLambdaImageConfig),
you're right, I'll fix this. I added my testing above. I thought I had tested the update case but I might've changed the type in one of my commits.

2023-09-22 21:26 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_aws_lambda_function.go
> +		ImageConfig:  d.Get("image_config").(*duplosdk.DuploLambdaImageConfig),
Fixed.

2023-09-23 00:08 UTC, joek-duplo requested changes
nice work adding the test suite, btw!

question on the image config stuff:
- does the backend not support updates to image config?  if not, this PR should be good already.
- if the backend *DOES* support updates to image config, we need to support it here too

2023-09-25 22:21 UTC, ddiaz-duplo commented
> nice work adding the test suite, btw!
> 
> question on the image config stuff:
> 
> * does the backend not support updates to image config?  if not, this PR should be good already.
> * if the backend _DOES_ support updates to image config, we need to support it here too

I’m only seeing one endpoint `subscriptions/{tenant_id}/UpdateLambdaFunctionConfiguration`
Action: `HttpPost` and thats the one used in the TF code.
[TF Code](https://github.com/duplocloud/terraform-provider-duplocloud/blob/515f2a43a7cec2a6e2442a94698f2aca07a69b9d/duplosdk/aws_lambda_function.go#L169)
[C# Code](https://github.com/duplocloud-internal/duplo/blob/00e8ae380d6d6c52ca7759ec18e4baf5f4a9c81a/ContainerManagement/Containers/Api/Controllers/ContainersTenantApiController.cs#L2163)

2023-09-27 18:49 UTC, joek-duplo approved these changes

2023-09-27 18:49 UTC, merged