update v1 -> v3 api
duplocloud/terraform-provider-duplocloud pull request #305
Opened 2023-09-18 19:39 UTC by ddiaz-duplo

## Change description

Update to v3 api which returns a more accurate `status_code` and `message`

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-09-18 19:39 UTC, zafarabbas commented
Task linked: [DUPLO-11479 TF: Replace v1 adminproxy/GetTenant with v3/admin/tenant/{t_id}/metadata](https://app.clickup.com/t/8655600/DUPLO-11479)

2023-09-19 20:29 UTC, joek-duplo requested changes

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var list []DuploTenant
revert this, since it makes the `list` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var list []DuploKeyStringValue
revert this, since it makes the `list` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var list []string
revert this, since it makes the `list` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var list []string
revert this, since it makes the `list` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var list []DuploTenantExtConnSecurityGroupRule
revert this, since it makes the `list` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var rp []DuploKeyStringValue
revert this, since it makes the `rp` initially `nil`

2023-09-19 20:29 UTC, joek-duplo commented on duplosdk/tenant.go
> +	var rp []DuploKeyStringValue
revert this, since it makes the `rp` initially `nil`

2023-09-20 16:56 UTC, joekhoobyar approved these changes

2023-09-20 16:58 UTC, joek-duplo approved these changes

2023-09-20 16:58 UTC, merged