Postgresql and microsoft sql server added.
duplocloud/terraform-provider-duplocloud pull request #31
Opened 2021-11-26 07:47 UTC by tahir-duplo

- New Resource: duplocloud_azure_postgresql_database added to manage a PostgreSQL database in Duplo.
- - New Resource: duplocloud_azure_mssql_database added to manage a Microsoft SQL server in Duplo.

2021-11-26 17:39 UTC, joek-duplo requested changes

2021-11-26 17:39 UTC, joek-duplo commented on duplocloud/resource_duplo_azure_mssql_database.go
> +	flattenAzureMssqlDatabase(d, duplo)
I noticed that we only read two fields here.  This will prevent `terraform import` commands from working.  Read is also used for import commands.

2021-11-27 06:17 UTC, tahir-duplo commented on duplocloud/resource_duplo_azure_mssql_database.go
> +	flattenAzureMssqlDatabase(d, duplo)
Done.

2021-11-27 23:53 UTC, joek-duplo approved these changes

2021-11-27 23:53 UTC, merged