wip
duplocloud/terraform-provider-duplocloud pull request #311
Opened 2023-09-21 19:03 UTC by ddiaz-duplo

## Change description

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-09-21 19:03 UTC, zafarabbas commented
Task linked: [DUPLO-8877 TF: External port should not be required field for Target group only lb type](https://app.clickup.com/t/8655600/DUPLO-8877)

2023-09-22 17:32 UTC, joek-duplo requested changes

2023-09-22 17:32 UTC, joek-duplo commented on duplosdk/replication_controller.go
> +	ExternalPort              *int                      `json:"ExternalPort,omitempty"`
the backend will actually have it as `0`, right?  it's just an `int` on the backend isn't it?   we should match the backend - even though it's lame.

2023-09-22 20:24 UTC, ddiaz-duplo commented on duplosdk/replication_controller.go
> +	ExternalPort              *int                      `json:"ExternalPort,omitempty"`
The backend will not set it to 0 if you omit it from the JSON. It sets it to match the `Port`. 

# Testing
Run this curl command to see result. Note that I set `Port` to 81

## Call API
```bash
curl --location 'https://test19.duplocloud.net/subscriptions/81386040-9a07-4e76-a195-94191d9d47aa/LBconfigurationBulkUpdate' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxxxxx' \
--data '{
    "TenantId":"81386040-9a07-4e76-a195-94191d9d47aa",
    "Name":"myservice",
    "LBConfigurations":
    [
        {
            "TenantId":"81386040-9a07-4e76-a195-94191d9d47aa",
            "ReplicationControllerName":"myservice",
            "LbType":7,
            "Protocol":"http",
            "Port":"81",
            "HostPort":0,
            "HealthCheckUrl":"/",
            "LbIndex":0,
            "ExtraSelectorLabels":null
        }
    ]
}'
```

## Results

![image](https://github.com/duplocloud/terraform-provider-duplocloud/assets/139073216/bd75901d-ad3b-4add-a63a-0da908651111)

2023-09-23 00:11 UTC, joek-duplo approved these changes
nice work, and you proved me to wrong to prevent a regression I would have caused.  thanks!

2023-09-23 00:11 UTC, merged