Duplo 10598 k8s jobs cronjobs
duplocloud/terraform-provider-duplocloud pull request #331
Opened 2023-10-20 14:41 UTC by ddiaz-duplo

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-10-20 14:41 UTC, zafarabbas commented
Task linked: [DUPLO-10598 TF: K8s Jobs + Cronjobs Support](https://app.clickup.com/t/8655600/DUPLO-10598)

2023-10-20 18:48 UTC, joek-duplo reviewed
LGTM

2023-10-21 06:30 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	if err != nil {
If the backend API error code is 404 on delete, Terraform should successfully destroy the resource.

2023-10-21 06:33 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	diags := waitForResourceToBePresentAfterCreate(ctx, d, "k8s job", id, func() (interface{}, duplosdk.ClientError) {
Are we not waiting for k8s job status "complete"?

2023-10-21 06:36 UTC, tahir-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +		"wait_for_completion": {
Are we not using wait_for_completion flag for wait ?

2023-10-21 19:52 UTC, joek-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	if err != nil {
Yes, @tahir-duplo is right.  This also reduces support requests from customers.

2023-10-21 19:53 UTC, joek-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	diags := waitForResourceToBePresentAfterCreate(ctx, d, "k8s job", id, func() (interface{}, duplosdk.ClientError) {
We definitely need an optional feature for that. @ddiaz-duplo can add that?  Should be easy right?

2023-10-21 19:54 UTC, joek-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +		"wait_for_completion": {
We need to

2023-10-21 19:55 UTC, joek-duplo requested changes
See @tahir-duplo 's comments

2023-10-23 16:50 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	diags := waitForResourceToBePresentAfterCreate(ctx, d, "k8s job", id, func() (interface{}, duplosdk.ClientError) {
Should we wait for a job complete status? I would think that important thing would be to wait for it to be available to query or view in the UI.

Job complete could take many minutes depending on the type of workload.

2023-10-23 17:37 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +		"wait_for_completion": {
ah, didn't see Joes reply. ok i'll implement that

2023-10-23 17:38 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_k8s_job.go
> +	diags := waitForResourceToBePresentAfterCreate(ctx, d, "k8s job", id, func() (interface{}, duplosdk.ClientError) {
didn't see Joe's comment, I'll implement it now.

2023-10-23 20:55 UTC, joek-duplo approved these changes

2023-10-23 20:55 UTC, merged