DUPLO-13027: update documentation duplocloud_aws_ssm_parameter move value from optional to required
duplocloud/terraform-provider-duplocloud pull request #338
Opened 2023-11-29 21:38 UTC by cbseirani-duplo

2023-11-29 21:38 UTC, zafarabbas commented
Task linked: [DUPLO-13027 TF: Doc: SSM Parameter: Value is not optional as mentioned in document](https://app.clickup.com/t/8655600/DUPLO-13027)

2023-11-29 21:50 UTC, ddiaz-duplo requested changes

2023-11-29 21:50 UTC, ddiaz-duplo commented on docs/resources/aws_ssm_parameter.md
> -- `value` (String) The value of the SSM parameter.
We generally don't modify the markup files directly. 
Make the change to the resource itself https://github.com/duplocloud/terraform-provider-duplocloud/blob/develop/duplocloud/resource_duplo_aws_ssm_parameter.go#L42
then run:
```sh
make doc
```
To generate the updated `aws_ssm_paramter.md` file

2023-11-29 21:55 UTC, joek-duplo requested changes
See David's change request.

2023-11-30 15:27 UTC, cbseirani-duplo commented on docs/resources/aws_ssm_parameter.md
> -- `value` (String) The value of the SSM parameter.
tyty

2023-11-30 15:32 UTC, closed without merging