DUPLO-10291 Update friednly name attributes and needs. Update check.
duplocloud/terraform-provider-duplocloud pull request #352
Opened 2023-12-20 15:57 UTC by sum-duplocloud

DUPLO-10291 Update friendly name attributes and "needs" update check.

2023-12-20 15:57 UTC, zafarabbas commented
Task linked: [DUPLO-10291 TF: Changes to ASG friendly_name don't trigger updates](https://app.clickup.com/t/8655600/DUPLO-10291)

2023-12-20 19:26 UTC, joek-duplo requested changes

2023-12-20 19:26 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +			DiffSuppressFunc: diffSuppressWhenNew,
This doesn't solve the problem, though.  If we send `myname`, duplo returns back `duploservices-TENANTNAME-myname`.  We need custom diff logic to solve this problem.

2023-12-21 15:18 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +			DiffSuppressFunc: diffSuppressWhenNew,
No, it doesn't work that way.  Let's talk in office hours, I will explain how TF performs diffs.

2023-12-27 19:52 UTC, joek-duplo requested changes

2023-12-27 19:52 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +func diffSuppressIfSame(k, old, new string, d *schema.ResourceData) bool {
I believe that `old` is the state from duplo, and `new` is the config specified by the user.  That being considered, I do not feel we are handling the cases properly.

- EQUAL: duplo:  `duploservices-TENANT-foobar`, user: `foobar`
- EQUAL: duplo:  `duploservices-TENANT-foobar`, user: `duploservices-TENANT-foobar`

2023-12-27 19:52 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +	if len(friendlyNameParts) == 3 {
`new` comes from the user.  what if the name is `my-cool-name`?  then, we will have 3 parts, but we will be missing the `duploservices-`.
also, what if the tenant name is `my-bad-name`?  then we would have a prefix of `duploservices-my-bad-name`.

your only choice here is to actually lookup the tenant name and calculate the prefix yourself.

we actually have code in this TF provider that does that, too.

2023-12-27 19:52 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +		return old == friendlyNameParts[2] // e.g.: tftestasg01
this backwards, I think.  `old` is from duplo, so it will always have the prefix.  now you are comparing it against a shortened value.

2024-01-02 15:55 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +		return old == friendlyNameParts[2] // e.g.: tftestasg01
USER CONFIG (new)

friendly_name = "joe1"

-OR-

friendly_name = "duploservices-mytenant-joe1"


STATE (old)

friendly_name = "duploservices-mytenant-joe1"

2024-01-02 15:55 UTC, joek-duplo commented
USER CONFIG (new)

friendly_name = "joe1"

-OR-

friendly_name = "duploservices-mytenant-joe1"


STATE (old)

friendly_name = "duploservices-mytenant-joe1"

2024-01-03 22:27 UTC, joek-duplo requested changes

2024-01-03 22:27 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +	if strings.Contains(new, "duploservices-") {
we should check if it `StartsWith` not `Contains`

2024-01-03 22:27 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +	friendlyNameParts := strings.SplitN(oldFullName, "-", 3)
oldFullName:  what if the tenant name is `joe-tenant`?  Then this split call will have `oldFullName` equal to `duploservices-joe-tenant-tftestasg01`, and will return `["duploservices","joe","tenant-tftestasg01"]`, and you will be comparing. `"tenant-tftestasg01"` to `"tftestasg01"` and it will fail.

2024-01-08 21:34 UTC, joek-duplo requested changes

2024-01-08 21:34 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_host.go
> +		return friendlyNameParts[len(friendlyNameParts)-1] == new
this doesn't look right either.  to compare `duploservices-MY-TENANT-host-name` with `host-name` or `duploservices-MYTENANT-hostname` you should just use our unprefix utility methods to remove the prefix from `oldFullName` or prefix utility methods to add the prefix to `new`.  the above logic won't work properly.

2024-01-08 21:39 UTC, joek-duplo approved these changes

2024-01-08 21:40 UTC, merged