DUPLO-10776: add support for tenant cleanup timers
duplocloud/terraform-provider-duplocloud pull request #354
Opened 2023-12-27 22:42 UTC by ddiaz-duplo

2023-12-27 22:42 UTC, zafarabbas commented
Task linked: [DUPLO-10776 TF: Support for Set Tenant expiration](https://app.clickup.com/t/8655600/DUPLO-10776)

2023-12-28 17:57 UTC, joek-duplo requested changes

2023-12-28 17:57 UTC, joek-duplo commented on duplosdk/tenant.go
> -	err := c.getAPI(apiName, fmt.Sprintf("v2/admin/TenantV2/%s", tenantID), &rp)
Changing this method would require full regression testing of all TF resources that call this method.

I imagine that this has not been done?

2023-12-28 17:57 UTC, joek-duplo commented on duplocloud/resource_duplo_tenant_cleanup_timers.go
> +	id := d.Id()
I think we can just have the tenant GUID be the ID instead of this string?

2023-12-28 17:57 UTC, joek-duplo commented on duplocloud/resource_duplo_tenant_cleanup_timers.go
> +		d.SetId(fmt.Sprintf("v3/admin/tenant/%s", rq.TenantId))
I think we can just have the tenant GUID be the ID instead of this string?

2023-12-28 18:05 UTC, ddiaz-duplo commented on duplosdk/tenant.go
> -	err := c.getAPI(apiName, fmt.Sprintf("v2/admin/TenantV2/%s", tenantID), &rp)
you're right, I'll add a new API call instead since the v2 tenant api only returns this for my test tenant;
```
{
    "TenantId": "6fbf4068-aba8-4c70-8fd3-0b8a287a10e4",
    "AccountName": "expirytest",
    "PlanID": "east1"
}
```

2023-12-28 20:10 UTC, joek-duplo approved these changes
LGTM

2023-12-28 20:21 UTC, merged