DUPLO-13381 AWS spot instance support w/ duplo_asg_profile.use_spot_instances
duplocloud/terraform-provider-duplocloud pull request #364
Opened 2024-01-10 17:36 UTC by duplodavid

## Change description

AWS spot instance support for the `duplo_asg_profile` resource by adding the `use_spot_instances` attribute.

The default value is `false` and changing this value on a resource will force it to be recreated.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

Fix [DUPLO-13381](https://app.clickup.com/t/8655600/DUPLO-13381)

2024-01-10 17:36 UTC, zafarabbas commented
Task linked: [DUPLO-13381 TF: duplocloud_asg_profile resource: add support for Spot instance](https://app.clickup.com/t/8655600/DUPLO-13381)

2024-01-10 23:26 UTC, joek-duplo requested changes
spot price is missing

2024-01-11 20:44 UTC, duplodavid commented
@joek-duplo Added `max_spot_price` and updated PR description to also mention this. Thank you!

2024-01-12 18:33 UTC, joek-duplo approved these changes

2024-01-12 18:34 UTC, merged