DUPLO-12737: k8s job labels
duplocloud/terraform-provider-duplocloud pull request #366
Opened 2024-01-13 13:31 UTC by ddiaz-duplo

# Overview

- Fix job Update
  - We were previously not passing tenantId, the update would fail, and we recreated the resource.
- Fix labels
  - Exclude duplo generated labels. Apply diff to anything else.

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Testing
testing shows update of label
![image](https://github.com/duplocloud/terraform-provider-duplocloud/assets/139073216/c1e48d75-1379-474d-b5ac-bc46784a3b7c)

2024-01-13 13:31 UTC, zafarabbas commented
Task linked: [DUPLO-12737 TF: K8s job/Cron Job: don't force replacement of k8s job on labels ,annotations and container remove  change](https://app.clickup.com/t/8655600/DUPLO-12737)

2024-01-13 17:26 UTC, joek-duplo requested changes
Minor changes

2024-01-13 17:26 UTC, joek-duplo commented on examples/data-sources/duplocloud_k8s_job/data-source.tf
> +  spec {
The spec in a data source must be readonly and thus not specified by the user

2024-01-14 18:36 UTC, ddiaz-duplo commented on examples/data-sources/duplocloud_k8s_job/data-source.tf
> +  spec {
fixed.

2024-01-16 15:18 UTC, joek-duplo approved these changes

2024-01-16 15:18 UTC, merged