DUPLO-4661: Tag based resource handling for lambda function resource.
duplocloud/terraform-provider-duplocloud pull request #379
Opened 2024-01-24 13:31 UTC by tahir-duplo

## Change description

Lambda function name validation based on Tag-based resource handling is enabled or not.

## Type of change
- New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-01-24 13:31 UTC, zafarabbas commented
Task linked: [DUPLO-4661 Tag based resource handling for lambda function resource](https://app.clickup.com/t/8655600/DUPLO-4661)

2024-01-25 14:41 UTC, joek-duplo requested changes
fix CHANGELOG.md conflicts

2024-01-25 14:52 UTC, tahir-duplo commented
> fix CHANGELOG.md conflicts

Resolved.

2024-01-25 14:55 UTC, joek-duplo approved these changes

2024-01-25 14:55 UTC, merged