Cloudfront distribution support.
duplocloud/terraform-provider-duplocloud pull request #39
Opened 2022-01-12 16:09 UTC by tahir-duplo

- `duplocloud_aws_cloudfront_distribution` resource added.

2022-01-18 20:26 UTC, joek-duplo requested changes

2022-01-18 20:26 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +						Default:  "TLSv1",
@tahir-duplo  - we should instead use a default value that will pass compliance (`TLSv1.2_2019`)
@jeevzb  - can we do the same in the defaults for the Duplo backend / UI?

2022-01-18 20:26 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +						ValidateFunc: validation.StringInSlice([]string{
@tahir-duplo  - can we use a default value of `sni-only` here?
@jeevzb  - can we do the same in the defaults for the Duplo backend / UI?

2022-01-18 20:26 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +											"TLSv1.2",
@tahir-duplo - we should instead use a default value that will pass compliance (`TLSv1.2`)
@jeevzb - can we do the same in the defaults for the Duplo backend / UI?

2022-01-19 17:13 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +						ValidateFunc: validation.StringInSlice([]string{
TF changes are done.

2022-01-19 17:13 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +											"TLSv1.2",
TF changes are done.

2022-01-20 15:56 UTC, joek-duplo approved these changes

2022-01-20 15:56 UTC, merged