DUPLO-14936, DUPLO-14934
duplocloud/terraform-provider-duplocloud pull request #412
Opened 2024-02-16 15:39 UTC by michalpleszkun

## Overview

- Added example of usage for EFS lifecycles policies
- Removed transision_to_archive lifecycle policy

## Summary of changes

This PR does the following:

- ...
- ...

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-02-16 15:39 UTC, zafarabbas commented
Task linked: [DUPLO-14936 TF:efs_lifecycle_policy: getting error "One or more LifecyclePolicy objects specified are malformed" for `transition_to_archive` lifecycle policy ](https://app.clickup.com/t/8655600/DUPLO-14936)

2024-02-16 15:39 UTC, zafarabbas commented
Task linked: [DUPLO-14934 TF Document changes required for  `duplocloud_aws_efs_lifecycle_policy` resource](https://app.clickup.com/t/8655600/DUPLO-14934)

2024-02-16 18:46 UTC, joek-duplo requested changes

2024-02-16 18:46 UTC, joek-duplo commented on CHANGELOG.md
> +- Enhanced EFS lifecycle policies by adding detailed descriptions for `transition_to_ia` and `transition_to_primary_storage_class` policies.
TF provider changelog entries must have the TF resource name.  Please see the other entries for examples.
Also [see here](https://github.com/duplocloud-internal/wiki/wiki/ProductDevBranchAndReviewModel#changelogmd-maintenance-guidelines-and-requirements).

2024-02-16 18:46 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_efs_file_system.go
> -					"transition_to_archive": {
I don't think we can remove `transition_to_archive`, I believe this must continue to be supported.

2024-02-16 18:46 UTC, joek-duplo commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  transition_to_ia = "AFTER_7_DAYS"
code format:  fix indentation

2024-02-16 18:46 UTC, joek-duplo commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  transition_to_primary_storage_class = "AFTER_1_ACCESS"
code format:  fix indentation

2024-02-16 18:46 UTC, joek-duplo commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +resource "duplocloud_tenant" "myapp" {
we should also add an `import.sh` script file in addition to this `resource.tf` file

2024-02-20 00:42 UTC, michalpleszkun commented on duplocloud/resource_duplo_aws_efs_file_system.go
> -					"transition_to_archive": {
We can and we must. We are not able to set it and this is the reason of DUPLO-14936.

2024-02-20 15:40 UTC, michalpleszkun commented
/update_changelog

2024-02-20 17:52 UTC, joek-duplo requested changes

2024-02-20 17:52 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_efs_file_system.go
> -					"transition_to_archive": {
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#transition_to_archive

2024-02-20 17:52 UTC, joek-duplo commented on duplocloud/resource_duplo_aws_efs_file_system.go
> -					"transition_to_archive": {
why can AWS support this field, but Duplo cannot?

2024-02-21 15:43 UTC, joek-duplo requested changes

2024-02-21 15:43 UTC, joek-duplo commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  transition_to_archive = "AFTER_14_DAYS"
fix indentation

2024-02-21 15:43 UTC, joek-duplo commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  lifecycle_policy{
fix missing space before bracket

2024-02-26 17:08 UTC, michalpleszkun commented on CHANGELOG.md
> +- Enhanced EFS lifecycle policies by adding detailed descriptions for `transition_to_ia` and `transition_to_primary_storage_class` policies.
I think it is done.

2024-02-26 17:09 UTC, michalpleszkun commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  transition_to_primary_storage_class = "AFTER_1_ACCESS"
done

2024-02-26 17:09 UTC, michalpleszkun commented on examples/resources/duplocloud_aws_efs_lifecycle_policy/resource.tf
> +  transition_to_archive = "AFTER_14_DAYS"
done

2024-02-27 15:46 UTC, joek-duplo requested changes
This PR is still removing the `transition_to_archive` element - so I can't approve it yet.

2024-02-27 16:01 UTC, joek-duplo approved these changes

2024-02-27 16:02 UTC, joek-duplo approved these changes

2024-02-27 16:02 UTC, merged