Duplo 11508 RDS secret manager attribute bug fix
duplocloud/terraform-provider-duplocloud pull request #419
Opened 2024-02-26 07:34 UTC by Duplo-nikv

## Overview

Bug fix attribute store_details_in_secret_manager not getting set at duplo
## Summary of changes
Setting values for attribute store_details_in_secret_manager on resource create context and fetching value on resource read context for duplocloud_rds_instance
This PR does the following:

- Setting DuploRdsInstance.StoreDetailsInSecretManager in rdsInstanceFromState()
- Setting store_details_in_secret_manager in rdsInstanceToState()
## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-02-26 07:34 UTC, zafarabbas commented
Task linked: [DUPLO-11508 TF: RDS Save Password in SecretsManager Doesn't actually work](https://app.clickup.com/t/8655600/DUPLO-11508)

2024-02-26 07:58 UTC, tahir-duplo commented on duplocloud/resource_duplo_gcp_k8_node_pool.go
> +			Description:  "The GUID of the tenant that the cloud function will be created in.",
Please change the description. Add node pool instead of cloud function.

2024-02-26 08:22 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_k8_node_pool.go
> +			Description:  "The GUID of the tenant that the cloud function will be created in.",
done

2024-02-26 08:27 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_k8_node_pool.go
> +			Description:  "The GUID of the tenant that the cloud function will be created in.",
I will change here too

2024-02-26 08:30 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_k8_node_pool.go
> +			Description:  "The GUID of the tenant that the cloud function will be created in.",
done

2024-02-27 16:40 UTC, joek-duplo requested changes
This PR should not have any code for node pools at all. Please remove that and fix the changelog.

2024-02-27 16:54 UTC, joek-duplo approved these changes

2024-02-27 16:54 UTC, merged