DUPLO-10189: TF: V3 APIs for S3
duplocloud/terraform-provider-duplocloud pull request #422
Opened 2024-02-27 00:31 UTC by pravin-duplocloud

## Overview

DUPLO-10189: TF: V3 APIs for S3

## Summary of changes

This PR does the following:

- use v3 api

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- None

2024-02-27 00:31 UTC, zafarabbas commented
Task linked: [DUPLO-10189 TF: V3 APIs for S3](https://app.clickup.com/t/8655600/DUPLO-10189)

2024-02-27 16:07 UTC, joek-duplo commented
/review

2024-02-27 16:19 UTC, joek-duplo requested changes

2024-02-27 16:19 UTC, joek-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> -	d.Set("name", name)
removing the `name` field will likely break TF imports, since no `name` has been previously defined when you are importing a resource.

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/utils.go
> +func (c *Client) IsDuploServicesNameWithAws(name string) bool {
this function does not properly check if the AWS account ID suffix is present.  if that is not the intention of the function, then fix the comment and fix the function name.

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/tenant_aws_cloud_resources.go
> +	err = c.putAPI(apiName, fmt.Sprintf("v3/subscriptions/%s/aws/s3Bucket/%s", tenantID, fullname), &duplo, &rp)
The ticket is asking that we use V3 APIs, with a fallback to V1 APIs.
Instead this code is:
 - Using a V3 API
 - Not having any fallback

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/tenant_aws_cloud_resources.go
> +	err := c.getAPI(fmt.Sprintf("TenantGetS3Bucket(%s, %s)", tenantID, fullname),
The ticket is asking that we use V3 APIs, with a fallback to V1 APIs.
Instead this code is:
 - Using a V3 API
 - Not having any fallback

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/tenant_aws_cloud_resources.go
> +	features, _ := c.AdminGetSystemFeatures()
the new code calls `AdminGetSystemFeatures` multiple times.  Instead, maybe we can call it outside of this method, and just pass the features in to this method?

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/tenant_aws_cloud_resources.go
> +	return c.deleteAPI(
The ticket is asking that we use V3 APIs, with a fallback to V1 APIs.
Instead this code is:
 - Using a V3 API
 - Not having any fallback

2024-02-27 16:19 UTC, joek-duplo commented on duplosdk/tenant_aws_cloud_resources.go
>  		fmt.Sprintf("TenantCreateS3Bucket(%s, %s)", tenantID, duplo.Name),
The ticket is asking that we use V3 APIs, with a fallback to V1 APIs.
Instead this code is:
 - Using a V3 API
 - Not having any fallback

2024-02-27 16:19 UTC, joek-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +	duploObject := duplosdk.DuploS3BucketSettingsRequest{
I don't think this is the right create API request structure.  We actually support specifying tenant region, global region, and maybe even a different region.

2024-02-27 16:35 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +	duploObject := duplosdk.DuploS3BucketSettingsRequest{
yes ...
 testing new region field

2024-02-28 15:52 UTC, pravin-duplocloud commented
will recreate with backward compatibility to fallback on old multiple api

2024-02-28 15:53 UTC, closed without merging

2024-02-28 15:53 UTC, pravin-duplocloud commented
will recreate with backward compatibility to fallback on old multiple api