Duplo 11675 RDS Group Cluster Parameter support
duplocloud/terraform-provider-duplocloud pull request #424
Opened 2024-02-27 07:48 UTC by Duplo-nikv

## Overview
Support for Group Cluster Parameter for RDS resource

## Summary of changes
Added support to add cluster parameter group name for rds instance for aurora db's
This PR does the following:

-  Added `cluster_parameter_group_name` attribute to `duplo_rds_instance` schema
-  Setting `cluster_parameter_group_name` attribute in rdsInstanceToState()
-  Setting `cluster_parameter_group_name` attribute in rdsInstanceFromState()
-  Added example for `cluster_parameter_group_name`
- Updated doc

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-02-27 07:48 UTC, zafarabbas commented
Task linked: [DUPLO-11675 TF: Support RDS Cluster Parameter Group Name parameter](https://app.clickup.com/t/8655600/DUPLO-11675)

2024-02-27 16:09 UTC, joek-duplo requested changes
This PR should not have any code for node pools at all.  Please remove that and fix the changelog.

2024-02-28 16:32 UTC, Duplo-nikv commented on duplocloud/resource_duplo_rds_instance.go
> +	if isAuroraDB(d) {
isAuroraDB checks for multiple DB
DUPLO_RDS_ENGINE_AURORA_MYSQL                 = 8
DUPLO_RDS_ENGINE_AURORA_POSTGRESQL            = 9
DUPLO_RDS_ENGINE_AURORA_SERVERLESS_MYSQL      = 11
DUPLO_RDS_ENGINE_AURORA_SERVERLESS_POSTGRESQL = 12
AURORA = 16

other than aurora supported db's are
MySQL 
PostgreSQL
MsftSQL-Express
MsftSQL-Standard
MsftSQL-Web
DocumentDB
MariaDB

So should I remove the isAuroraDB check?

2024-03-01 16:38 UTC, joek-duplo commented on duplocloud/resource_duplo_rds_instance.go
> +	if isAuroraDB(d) {
no, my complaint was not to remove the aurora check, it was to include any additional DB that also supports a cluster parameter group name.  please check with @pravin-duplocloud , I believe he knows the logic here.

2024-03-01 17:13 UTC, Duplo-nikv commented
Yes I got the additional Db's talked with Praveen on this.

On Fri, Mar 1, 2024, 10:08 PM Joe Khoobyar ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In duplocloud/resource_duplo_rds_instance.go
> <https://github.com/duplocloud/terraform-provider-duplocloud/pull/424#discussion_r1509244285>
> :
>
> > @@ -624,6 +636,9 @@ func rdsInstanceFromState(d *schema.ResourceData) (*duplosdk.DuploRdsInstance, e
>  	duploObject.EngineVersion = d.Get("engine_version").(string)
>  	duploObject.SnapshotID = d.Get("snapshot_id").(string)
>  	duploObject.DBParameterGroupName = d.Get("parameter_group_name").(string)
> +	if isAuroraDB(d) {
>
> no, my complaint was not to remove the aurora check, it was to include any
> additional DB that also supports a cluster parameter group name. please
> check with @pravin-duplocloud <https://github.com/pravin-duplocloud> , I
> believe he knows the logic here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duplocloud/terraform-provider-duplocloud/pull/424#discussion_r1509244285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFXKLDMGE5JCDGL4RJXHG5TYWCVITAVCNFSM6AAAAABD3S6A3KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJRGU2TQMRVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> <duplocloud/terraform-provider-duplocloud/pull/424/review/1911558251@
> github.com>
>

2024-03-07 15:52 UTC, tahir-duplo approved these changes
LGTM

2024-03-07 16:48 UTC, Duplo-nikv commented on duplocloud/resource_duplo_rds_instance.go
> +	if isAuroraDB(d) {
Checked the UI for all databases which is associated with cluster group parameter along with @pravin-duplocloud 
https://github.com/duplocloud/terraform-provider-duplocloud/pull/424/commits/6f117b155ddd26ba6661b45b202c79cb7387a921

Nodepool code trace where removed

2024-03-07 16:54 UTC, merged