Duplo 13405 Terraform provider - duplocloud batch job definitions with revisions do not delete correctly
duplocloud/terraform-provider-duplocloud pull request #425
Opened 2024-02-27 11:31 UTC by Duplo-nikv

## Overview

Bug fix for Terraform gets timed out while destroying batch job resources

## Summary of changes
Terraform Job Deletion time out issue fixed
This PR does the following:

- When a change is made to the batch job that requires recreation, terraform  deletes all the revisions of the job and then recreate it.
 

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-02-27 11:31 UTC, zafarabbas commented
Task linked: [DUPLO-13405 Terraform provider - duplocloud batch job definitions with revisions do not delete correctly](https://app.clickup.com/t/8655600/DUPLO-13405)

2024-02-27 16:08 UTC, joek-duplo requested changes
This PR should not contain any changes for nodepools at all.   Please remove that and fix the changelog.

2024-03-11 08:46 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_batch_job_definition.go
> +			if clientErr.Status() == 404 {
We should just continue the loop in case of 404, for deletion of another revision here.

2024-03-11 09:21 UTC, Duplo-nikv commented on duplocloud/resource_duplo_aws_batch_job_definition.go
> +			if clientErr.Status() == 404 {
made changes
resolved conflicts

2024-03-11 09:43 UTC, tahir-duplo approved these changes
LGTM

2024-03-11 09:43 UTC, merged