DUPLO-10189: v3 api s3
duplocloud/terraform-provider-duplocloud pull request #431
Opened 2024-02-29 01:17 UTC by pravin-duplocloud

## Overview

DUPLO-10189: v3 api s3  

## Summary of changes

This PR does the following:

-  v3 api s3 
- fallback support to older api

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- None

2024-02-29 01:17 UTC, zafarabbas commented
Task linked: [DUPLO-10189 TF: V3 APIs for S3](https://app.clickup.com/t/8655600/DUPLO-10189)

2024-02-29 01:19 UTC, pravin-duplocloud commented
/review

2024-02-29 01:19 UTC, pravin-duplocloud commented
/update_changelog --pr_update_changelog.push_changelog_changes=true

2024-02-29 01:20 UTC, pravin-duplocloud commented
/describe

2024-03-05 00:53 UTC, ddiaz-duplo requested changes

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Unable get duplo services name with aws, tenant %s bucket '%s': %s", tenantID, name, err)
```suggestion
		return diag.Errorf("Unable to get duplo service name for tenant %s and bucket '%s': %s", tenantID, name, err)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +			return diag.Errorf("Unable to retrieve tenant %s bucket '%s': %s", tenantID, name, err)
```suggestion
			return diag.Errorf("Unable to retrieve bucket '%s' for tenant %s: %s", name, tenantID, err)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Error get duplo services name with aws '%s' error: '%s'", name, errname.Error())
```suggestion
		return diag.Errorf("Error retrieving duplo service name '%s' error: '%s'", name, errname.Error())
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Error applying tenant %s bucket '%s': %s", tenantID, duploObject.Name, err)
```suggestion
		return diag.Errorf("Error creating bucket %s for tenant '%s': %s", duploObject.Name, tenantID, err)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Expected length of s3 name '%s' to be in the range (1 - %d)", name, s3MaxLength)
```suggestion
		return diag.Errorf("Length of S3 bucket name '%s' must be in the range (1 - %d)", name, s3MaxLength)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Unable to retrieve tenant %s bucket '%s': %s", tenantID, name, err)
```suggestion
		return diag.Errorf("Unable to retrieve bucket '%s' for tenant %s: %s", tenantID, name, err)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Error applying tenant %s bucket '%s': %s", tenantID, duploObject.Name, err)
```suggestion
		return diag.Errorf("Error updating bucket '%s' for tenant %s: %s", tenantID, duploObject.Name, err)
```

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +	//features, _ := c.AdminGetSystemFeatures()
delete unused code

2024-03-05 00:53 UTC, ddiaz-duplo commented on duplosdk/tenant_aws_cloud_resources.go
> +		//  fmt.Sprintf("subscriptions/%s/S3BucketUpdate", tenantID),
remove commented out code

2024-03-21 17:40 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Unable get duplo services name with aws, tenant %s bucket '%s': %s", tenantID, name, err)
done

2024-03-21 17:43 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +			return diag.Errorf("Unable to retrieve tenant %s bucket '%s': %s", tenantID, name, err)
done

2024-03-21 17:43 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Error get duplo services name with aws '%s' error: '%s'", name, errname.Error())
done

2024-03-21 18:19 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Error applying tenant %s bucket '%s': %s", tenantID, duploObject.Name, err)
done

2024-03-21 18:19 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +		return diag.Errorf("Unable to retrieve tenant %s bucket '%s': %s", tenantID, name, err)
done

2024-03-21 18:19 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_s3_bucket.go
> +	//features, _ := c.AdminGetSystemFeatures()
done

2024-03-21 18:19 UTC, pravin-duplocloud commented on duplosdk/tenant_aws_cloud_resources.go
> +		//  fmt.Sprintf("subscriptions/%s/S3BucketUpdate", tenantID),
done

2024-03-21 20:30 UTC, tahir-duplo commented on docs/resources/s3_bucket.md
> +  # optional , if not provided, tenant region will be used
Add this in example and generate doc using `make doc`

2024-03-21 20:55 UTC, pravin-duplocloud commented on docs/resources/s3_bucket.md
> +  # optional , if not provided, tenant region will be used
done

2024-03-22 09:07 UTC, tahir-duplo approved these changes
LGTM

2024-03-22 09:07 UTC, merged