DUOLO-12802 Fix for Plan always show diff on duplocloud_plan_settings
duplocloud/terraform-provider-duplocloud pull request #472
Opened 2024-04-01 15:43 UTC by Duplo-nikv

## Overview

Fixed showing diff if no change
## Summary of changes

This PR does the following:

- made specified_metadata schema attribute optional along with computed and added diff suppress function
- ...

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-04-01 15:43 UTC, zafarabbas commented
Task linked: [DUPLO-12802 TF Plan always show diff on duplocloud_plan_settings [contextual]](https://app.clickup.com/t/8655600/DUPLO-12802)

2024-04-19 16:05 UTC, komalkadam-dc requested changes

2024-04-19 16:05 UTC, komalkadam-dc commented on duplocloud/resource_duplo_plan_settings.go
> +func diffSuppressSpecifiedMetadata(k, old, new string, d *schema.ResourceData) bool {
can we move it utils, as it can be used by other resources

2024-04-22 07:01 UTC, Duplo-nikv commented on duplocloud/resource_duplo_plan_settings.go
> +func diffSuppressSpecifiedMetadata(k, old, new string, d *schema.ResourceData) bool {
done

2024-04-22 08:42 UTC, komalkadam-dc approved these changes

2024-04-22 10:26 UTC, tahir-duplo approved these changes
LGTM

2024-04-22 10:26 UTC, merged