Duplo 16671 gcp application load balancer global access support
duplocloud/terraform-provider-duplocloud pull request #480
Opened 2024-04-05 13:41 UTC by Duplo-nikv

## Overview

gcp application load balancer global access support
## Summary of changes

This PR does the following:

- gcp application load balancer global access support
- changed waiting api, created new function , purpose not to break other code using older waiting api

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [✓ ] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-04-05 13:41 UTC, zafarabbas commented
Task linked: [DUPLO-16671 TF:support for global access attribute for ALB /Internal](https://app.clickup.com/t/8655600/DUPLO-16671)

2024-04-05 15:21 UTC, Duplo-nikv commented on duplocloud/resource_duplo_lbconfigs.go
response from lbdetails from gcp doesnt have State attribute, but aws has.
code logic explanation:
check if lbdetails has data
if source is aws then lbDetails will have State attribute if its not active poll
if source is gcp and lbdetails will not have State attribute, lbdetails only contains value once lb is active

2024-04-19 19:16 UTC, komalkadam-dc requested changes
rest of the PR looks good, please fix changelog

2024-04-19 19:16 UTC, komalkadam-dc commented on CHANGELOG.md
> +- Introduced support for `allow_global_access` attribute in GCP internal load balancer configurations.
Please add the proper resource name

2024-04-22 08:15 UTC, Duplo-nikv commented on CHANGELOG.md
> +- Introduced support for `allow_global_access` attribute in GCP internal load balancer configurations.
done

2024-04-22 08:43 UTC, komalkadam-dc approved these changes

2024-04-23 07:16 UTC, tahir-duplo commented on duplocloud/resource_duplo_lbconfigs.go
> +		},
Add computed here.

2024-04-23 07:22 UTC, Duplo-nikv commented on duplocloud/resource_duplo_lbconfigs.go
> +		},
done

2024-04-23 07:32 UTC, tahir-duplo commented on duplocloud/resource_duplo_lbconfigs.go
@Duplo-nikv I am not comfortable with this change, Have ou tested this for both AWS and GCP.

2024-04-23 08:56 UTC, tahir-duplo approved these changes
LGTM

2024-04-23 08:56 UTC, merged