Duplo 16117 Nodepool List Datasource Fix
duplocloud/terraform-provider-duplocloud pull request #484
Opened 2024-04-08 09:27 UTC by Duplo-nikv

## Overview

Fixed listing of Nodepools 
## Summary of changes

This PR does the following:

- updated document
- Fixed State not getting set for data source of node pools datasource

## Testing performed

- [ ] Using unit tests
- [ ✓] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-04-08 09:28 UTC, Duplo-nikv commented
Also fixed datasource for sqls and updated document

2024-04-22 06:29 UTC, komalkadam-dc requested changes

2024-04-22 06:29 UTC, komalkadam-dc commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	mp := map[string]interface{}{
do we need this declaration, we can directly return it

2024-04-22 08:18 UTC, Duplo-nikv commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	mp := map[string]interface{}{
yes its better to do so, to avoid nil pointer exception

2024-04-22 08:44 UTC, komalkadam-dc submitted a review, later dismissed

2024-04-25 08:36 UTC, tahir-duplo commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	fmt.Println("List ", list)
Please remove these console logs.

2024-04-25 08:38 UTC, tahir-duplo commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	mp := map[string]interface{}{
@Duplo-nikv Komal is right here. You just have to return map struct.

2024-04-25 08:41 UTC, Duplo-nikv commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	mp := map[string]interface{}{
It was not initializing the values, when used as return so I changed it in this way, which worked

2024-04-25 09:58 UTC, Duplo-nikv commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	fmt.Println("List ", list)
done

2024-04-25 09:59 UTC, Duplo-nikv commented on duplocloud/data_source_duplo_gcp_node_pools.go
> +	mp := map[string]interface{}{
done

2024-04-25 10:05 UTC, merged