Duplo 16561 GCP Firestore Resource
duplocloud/terraform-provider-duplocloud pull request #492
Opened 2024-04-11 08:16 UTC by Duplo-nikv

## Overview

GCP Firestore Resource implementation
## Summary of changes
Added CURD support for GCP Firestore Resource `duplocloud_gcp_firestore`
This PR does the following:

- Implemented resource for gcp firestore 
- Implemented data-source for gcp firestore

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [✓ ] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-04-11 08:16 UTC, zafarabbas commented
Task linked: [DUPLO-16561 [TF] GCP: Support for Firestore DB](https://app.clickup.com/t/8655600/DUPLO-16561)

2024-04-19 15:41 UTC, komalkadam-dc commented on docs/resources/gcp_firestore.md
> +- `type` (String) Firestore type
add possible values

2024-04-19 15:44 UTC, komalkadam-dc requested changes
Add possible values for type, rest looks good

2024-04-22 06:10 UTC, Duplo-nikv commented on docs/resources/gcp_firestore.md
> +- `type` (String) Firestore type
done

2024-04-22 06:23 UTC, komalkadam-dc approved these changes

2024-04-25 12:07 UTC, tahir-duplo approved these changes
LGTM

2024-04-25 12:07 UTC, merged