DUPLO-17432 Terraform duplocloud_k8s_job resource can't mount secrets as file
duplocloud/terraform-provider-duplocloud pull request #570
Opened 2024-06-26 06:26 UTC by Duplo-nikv

## Overview

Fixed volume mount issue
## Summary of changes

This PR does the following:

- Managed volume and volume mount attribute.
- Updated docs

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-06-26 06:26 UTC, zafarabbas commented
Task linked: [DUPLO-17432 Terraform duplocloud_k8s_job resource can't mount secrets as file](https://app.clickup.com/t/8655600/DUPLO-17432)

2024-06-26 09:15 UTC, tahir-duplo commented on README.md
Why are we deleting readme?

2024-06-26 10:11 UTC, Duplo-nikv commented on README.md
May be got deleted by mistake while deleting state file while testing

2024-06-27 11:10 UTC, komalkadam-dc requested changes

2024-06-27 11:10 UTC, komalkadam-dc commented on README.md
> +
Remove this line

2024-06-27 11:10 UTC, komalkadam-dc commented on duplocloud/utils.go
> +	for i, digit := range octal {
shouldn't we add a validation to check if the octal string contains only number(i.e. octal number), it should prompt error for wrong input if it contains character

2024-07-05 05:37 UTC, tahir-duplo commented on duplocloud/utils.go
> +	for i, digit := range octal {
@Duplo-nikv Can we change this logic to 
```
func ValidateOctalString(s string) bool {
    // Regular expression to match an octal string (0-7 digits)
    re := regexp.MustCompile(`^[0-7]+$`)
    return re.MatchString(s)
}
```

The comparison `if digit < '0' || digit > '7'` might fail with `mismatched types string and untyped rune`

2024-07-08 06:07 UTC, komalkadam-dc commented on duplocloud/structures_k8s_container.go
> +		if v, ok := ctr["volume_mount"].([]interface{}); ok && len(v) > 0 {
what will happen in case of volume mount is null, will this throw an exception?

2024-07-08 07:03 UTC, Duplo-nikv commented on duplocloud/structures_k8s_container.go
> +		if v, ok := ctr["volume_mount"].([]interface{}); ok && len(v) > 0 {
I dont see any error returning. It will be always null. I just uncommented this part of code which is required to volume mount. It worked after uncommenting it

2024-07-09 07:03 UTC, tahir-duplo approved these changes
LGTM

2024-07-09 10:37 UTC, merged