Duplo-18045 TF: GCP: Add Terraform support to create bucket with multi region and region
duplocloud/terraform-provider-duplocloud pull request #571
Opened 2024-06-26 14:28 UTC by Duplo-nikv

## Overview

Implemented `duplocloud_gcp_s3_bucket` resource with multi region support
## Summary of changes

This PR does the following:

- Implemented duplocloud_gcp_s3_bucket resource operations
- Updated docs with multi region example

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-06-27 11:02 UTC, komalkadam-dc requested changes

2024-06-27 11:02 UTC, komalkadam-dc commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
I don't see this attribute supported for S3 bucket.

2024-06-27 15:18 UTC, Duplo-nikv commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
<img width="1126" alt="Screenshot 2024-06-27 at 20 47 25" src="https://github.com/duplocloud/terraform-provider-duplocloud/assets/158246285/4e0555eb-a25c-493c-950d-8dbe690268ff">
It was in qa-gcp its been changed to different release, but found in qa-gcp2. Check attachment

2024-06-27 16:33 UTC, komalkadam-dc commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
isn't it AWS s3 bucket?
I was saying this attribute is not present for AWS S3 bucket, its present gcp

2024-07-03 09:02 UTC, Duplo-nikv commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
Its gcp specific

2024-07-03 17:30 UTC, tahir-duplo commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
@Duplo-nikv Let remove location from `resourceS3BucketSetData` method and new gcp specific method say `resourceS3GcpBucketSetData`

2024-07-04 04:49 UTC, Duplo-nikv commented on duplocloud/resource_duplo_s3_bucket.go
> +	d.Set("location", duplo.Location)
done changes

2024-07-05 07:15 UTC, tahir-duplo approved these changes
LGTM

2024-07-08 06:04 UTC, komalkadam-dc approved these changes

2024-07-09 06:56 UTC, merged