DUPLO-16119 Add name to duplocloud_aws_cloudfront_distribution
duplocloud/terraform-provider-duplocloud pull request #589
Opened 2024-07-12 13:15 UTC by Duplo-nikv

## Overview

Added name attribute, made comment attribute depreciated
## Summary of changes

This PR does the following:

- added name attribute in duplocloud_aws_cloudfront_distribution resource schema
- made comment attribute depreceated

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-07-12 13:15 UTC, zafarabbas commented
Task linked: [DUPLO-16119 [TF ] Add name to duplocloud_aws_cloudfront_distribution](https://app.clickup.com/t/8655600/DUPLO-16119)

2024-07-15 05:00 UTC, zafarabbas requested changes

2024-07-15 05:00 UTC, zafarabbas commented on docs/resources/aws_cloudfront_distribution.md
> +- `comment` (String, Deprecated) Any comments you want to include about the distribution. comment has been depreciated instead use name
typo: `deprecated`

2024-07-15 05:00 UTC, zafarabbas commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +			Deprecated:   "comment has been depreciated instead use name",
typo: `deprecated`

2024-07-15 13:10 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		"name": {
We should not add the required attribute `name`, We are forcing existing customer code to be modified on provider upgrade. Instead we can add optional name attribute  `ConflictsWith` comment attribute.

2024-07-15 14:14 UTC, Duplo-nikv commented
Ticket mentioned to make it required

On Mon, Jul 15, 2024, 6:40 PM Tahir Tamboli ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In duplocloud/resource_duplo_aws_cloudfront_distribution.go
> <https://github.com/duplocloud/terraform-provider-duplocloud/pull/589#discussion_r1677804578>
> :
>
> > @@ -49,6 +49,13 @@ func duploAwsCloudfrontDistributionSchema() map[string]*schema.Schema {
>  			Optional:     true,
>  			Computed:     true,
>  			ValidateFunc: validation.StringLenBetween(0, 128),
> +			Deprecated:   "comment has been depreciated instead use name",
> +		},
> +		"name": {
>
> We should not add the required attribute name, We are forcing existing
> customer code to be modified on provider upgrade. Instead we can add
> optional name attribute ConflictsWith comment attribute.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duplocloud/terraform-provider-duplocloud/pull/589#pullrequestreview-2177675460>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFXKLDMKZ7KWSEUB265ENVLZMPC5BAVCNFSM6AAAAABKY5G7RGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZXGY3TKNBWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> <duplocloud/terraform-provider-duplocloud/pull/589/review/2177675460@
> github.com>
>

2024-07-15 19:19 UTC, zafarabbas commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		"name": {
@tahir-duplo should we even deprecate `comment` in this version?

2024-07-16 05:16 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		"name": {
Yes, We should deprecate `comment`

2024-07-16 17:06 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +	distributionConfig.Comment = d.Get("name").(string)
@Duplo-nikv We should add a check if the name is provided use name or a comment.

2024-07-17 16:01 UTC, zafarabbas approved these changes

2024-07-17 16:01 UTC, zafarabbas commented
@tahir-duplo can you review again?

2024-07-17 16:09 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_cloudfront_distribution.go
> +		d.Set("name", duplo.Comment)
We should either set `comment` or `name`.

2024-07-23 06:50 UTC, merged