New resource duplocloud_plan_settings added.
duplocloud/terraform-provider-duplocloud pull request #63
Opened 2022-03-30 22:50 UTC by tahir-duplo

New resource duplocloud_plan_settings added.

2022-03-30 22:52 UTC, zafarabbas commented
Task linked: [DUPLO-2959 Need a duplocloud_plan_settings resource](https://app.clickup.com/t/8655600/DUPLO-2959)

2022-03-31 03:52 UTC, joek-duplo requested changes

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_lbconfigs.go
> +				if lb.LbType != 0 && lb.LbType != 2 && lb.LbType != 3 && lb.LbType != 4 {
Can we keep this out of this PR?  It is already on another PR, that I commented on.

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
We should not check for possible missing API here, just let it an error.  Possible missing API checks are meant to "fallback" from newer APIs to older APIs - and this is an old API with no alternative.

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
We should not check for possible missing API here, just let it an error.  Possible missing API checks are meant to "fallback" from newer APIs to older APIs - and this is an old API with no alternative.

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if _, ok := d.GetOk("unrestricted_ext_lb"); ok {
We should check for a nil `duplo` result from the API call. If nil, skip the delete operation.

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if v, ok := d.GetOk("unrestricted_ext_lb"); ok {
We should check for a nil `duplo` result from the API call. If nil, the provider should return an error that the plan could not be found.

2022-03-31 03:52 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
We should not check for possible missing API here, just let it an error.  Possible missing API checks are meant to "fallback" from newer APIs to older APIs - and this is an old API with no alternative.

2022-03-31 06:11 UTC, tahir-duplo commented on duplocloud/resource_duplo_lbconfigs.go
> +				if lb.LbType != 0 && lb.LbType != 2 && lb.LbType != 3 && lb.LbType != 4 {
Done.

2022-03-31 06:11 UTC, tahir-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
Done.

2022-03-31 06:11 UTC, tahir-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
Done.

2022-03-31 06:12 UTC, tahir-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if v, ok := d.GetOk("unrestricted_ext_lb"); ok {
Done.

2022-03-31 06:12 UTC, tahir-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if err != nil && !err.PossibleMissingAPI() {
Done.

2022-04-01 00:50 UTC, joek-duplo requested changes

2022-04-01 00:50 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if duplo == nil {
The error check must come before the `duplo` nil check, or we end up not reporting errors to the user.

2022-04-01 00:50 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if duplo == nil {
The error check must come before the `duplo` nil check, or we end up not reporting errors to the user.

2022-04-01 00:50 UTC, joek-duplo commented on duplocloud/resource_duplo_plan_settings.go
> +	if duplo == nil {
The error check must come before the `duplo` nil check, or we end up not reporting errors to the user.

2022-04-01 01:55 UTC, joek-duplo approved these changes

2022-04-01 01:55 UTC, joek-duplo approved these changes

2022-04-01 01:58 UTC, joek-duplo approved these changes

2022-04-01 01:59 UTC, merged