DUPLO-20918: [Avialabilty Zone] RDS primary and replica to support AZ zone
duplocloud/terraform-provider-duplocloud pull request #648
Opened 2024-08-28 20:01 UTC by pravin-duplocloud

DUPLO-20918: [Avialabilty Zone] RDS primary and replica to support AZ zone

## Overview

... (don't forget to put your clickup ticket ID in the title) ...

## Summary of changes

This PR does the following:

- availability zone for aurora writer
- availability zone for rds primary

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-08-29 16:40 UTC, zafarabbas requested changes

2024-08-29 16:40 UTC, zafarabbas commented on docs/resources/rds_instance.md
> +  availability_zone = true
This is not a boolean, its an AZ right?

2024-08-29 18:27 UTC, zafarabbas requested changes

2024-08-29 18:27 UTC, zafarabbas commented on docs/resources/rds_instance.md
> +  availability_zone = us-west-2a
we can remove the comment from the example, the field is already documented below in detail, this clutters the example code unnecessarily

2024-08-29 19:57 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +  availability_zone = us-west-2a
done

2024-08-29 20:02 UTC, zafarabbas commented on docs/resources/rds_instance.md
> +  availability_zone       = us-west-2a
is zone supposed to be a string like “us-west-2a”?

2024-08-30 05:02 UTC, Duplo-nikv requested changes

2024-08-30 05:02 UTC, Duplo-nikv commented on duplocloud/resource_duplo_rds_instance.go
>  	}
I think availability_zone should be set [us-west-2a,us-west-2b]

2024-08-30 05:24 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +  availability_zone = true
done

2024-08-30 05:24 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +  availability_zone = us-west-2a
done

2024-08-30 05:27 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_instance.go
>  	}
this is for rds primary and aurora write specifically, not considering  cluster.
- customer want to control master in default zone and fialover replica in another zone.

2024-08-30 05:31 UTC, zafarabbas submitted a review, later dismissed

2024-08-30 09:20 UTC, Duplo-nikv approved these changes
LGTM

2024-08-30 09:20 UTC, Duplo-nikv commented on duplocloud/resource_duplo_rds_instance.go
>  	}
ok closing based on the discussion

2024-08-30 17:55 UTC, tahir-duplo approved these changes
LGTM

2024-08-30 17:55 UTC, merged

2024-08-30 17:57 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +  availability_zone       = us-west-2a
done