DUPLO-21167: add new airflow versions and remove deprecated versions
duplocloud/terraform-provider-duplocloud pull request #694
Opened 2024-09-09 23:33 UTC by pravin-duplocloud

## Overview

DUPLO-21167: add new airflow versions and remove deprecated versions

## Summary of changes

This PR does the following:

- add new airflow versions and remove deprecated versions
- add new instance size

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- None

2024-09-09 23:34 UTC, zafarabbas commented
Task linked: [DUPLO-21167 Update Airflow version to all supported](https://app.clickup.com/t/8655600/DUPLO-21167)

2024-09-10 01:25 UTC, sp1676 requested changes

2024-09-10 01:25 UTC, sp1676 commented on duplocloud/resource_duplo_aws_mwaa_environment.go
>  			Description: "Environment class for the cluster. Possible options are `mw1.small`, `mw1.medium`, `mw1.large`.",
Description should be changed as well.

2024-09-10 04:42 UTC, tahir-duplo commented on duplocloud/resource_duplo_aws_mwaa_environment.go
>  			Description: "Environment class for the cluster. Possible options are `mw1.small`, `mw1.medium`, `mw1.large`.",
Done

2024-09-10 04:42 UTC, tahir-duplo approved these changes
LGTM

2024-09-10 04:45 UTC, merged