DUPLO-21305 TF: Support aurora-iopt1 storage type for duplocloud_rds_instance
duplocloud/terraform-provider-duplocloud pull request #713
Opened 2024-09-19 05:38 UTC by Duplo-nikv

## Overview

Added support for aurora-iopt1 for aurora-mysql and aurora-postgresql 
## Summary of changes
Added support for aurora-iopt1 for aurora-mysql and aurora-postgresql with version support duplocloud_rds_instance

This PR does the following:

- Added aurora-iopt1 to storage_type validation
- Updated logic in customdiff function to handle the supported version of storage type and throw user friendly error on plan
- tested for aurora psql on backend branch feturw/DUPLO-21306-supprt-aurora-iopt1-storage-type
## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

2024-09-19 05:38 UTC, zafarabbas commented
Task linked: [DUPLO-21305 TF: Support aurora-iopt1 storage type for duplocloud_rds_instance](https://app.clickup.com/t/8655600/DUPLO-21305)
Task linked: [DUPLO-21306 BE: Support aurora-iopt1 storage type](https://app.clickup.com/t/8655600/DUPLO-21306)

2024-09-25 14:26 UTC, pravin-duplocloud requested changes

2024-09-25 14:26 UTC, pravin-duplocloud commented on docs/resources/rds_instance.md
> +- `storage_type` (String) Valid values: gp2 | gp3 | io1 | standard | aurora | aurora-iopt1. Storage type to be used for RDS instance storage.
- can you add more on storage_type
- Aurora: 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.storage-type.html
- RDS: 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html

<img width="633" alt="image" src="https://github.com/user-attachments/assets/ca9c8e28-4689-486c-b27e-6d7e7d2f5b69">

2024-09-25 14:26 UTC, pravin-duplocloud commented on duplocloud/utils.go
> +func extractVersion(input string) string {
-  can you move version utility methods into => version_utils.go

2024-09-27 06:00 UTC, Duplo-nikv commented on duplocloud/resource_duplo_rds_instance.go
> +				[]string{"gp2", "gp3", "io1", "standard", "aurora", "aurora-iopt1"},
Its validating value of storage type I added aurora-iopt1 as additional storage type

2024-09-27 06:44 UTC, Duplo-nikv commented on duplocloud/utils.go
> +func extractVersion(input string) string {
moved from utils to version_utils file

2024-09-27 06:45 UTC, Duplo-nikv commented on docs/resources/rds_instance.md
> +- `storage_type` (String) Valid values: gp2 | gp3 | io1 | standard | aurora | aurora-iopt1. Storage type to be used for RDS instance storage.
done

2024-09-27 08:28 UTC, tahir-duplo submitted a review, later dismissed
LGTM

2024-10-04 15:07 UTC, pravin-duplocloud submitted a review, later dismissed

2024-10-04 15:07 UTC, pravin-duplocloud commented on duplocloud/version_utils.go
> +package duplocloud
already exists 
terraform-provider-duplocloud/duplosdk/version_utils.go
can you merge them

2024-10-04 15:16 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_rds_instance.go
> +				[]string{"gp2", "gp3", "io1", "standard", "aurora", "aurora-iopt1"},
this is how we did it in backend
private void ValidateAuroraIopt1()
{
    if (!string.Equals(StorageType, "aurora-iopt1"))
        return;

    var error = $"Invalid Aurora engine version, StorageType 'aurora-iopt1' not supported for '{EngineVersion}'";
    if (Engine == DBEngine.AuroraMySql && EngineVersion?.IndexOf(".mysql_aurora.") > 0)
    {
        //  '5.7.mysql_aurora.2.11.1'
        var vers = EngineVersion.Split(new[] { ".mysql_aurora." }, StringSplitOptions.None);
        var version = vers.Last();
        var verCurrent = Utils.ParseVersion(version);
        // Aurora MySQL version 3.03.1 and higher
        if (verCurrent.Major > 3)
            return;
        if ( verCurrent.Major < 3
            || string.Equals(version, "3.03.0")
            || !Utils.IsCurrentMajorMinorVersionNewerOrEqualTo(version, "3.03.1"))
            throw new InvalidDataException(error);
    }

    if (Engine == DBEngine.AuroraPostgreSql)
    {
        var verCurrent = Utils.ParseVersion(EngineVersion);
        if (verCurrent.Major > 17)
            return;
        // Aurora PostgreSQL versions 16.1 and higher, 15.2 and higher, 14.7 and higher, and 13.10 and higher
        if (verCurrent.Major < 13
            || verCurrent.Major == 13 && !Utils.IsCurrentMajorMinorVersionNewerOrEqualTo(EngineVersion, "13.10")
            || verCurrent.Major == 14 && !Utils.IsCurrentMajorMinorVersionNewerOrEqualTo(EngineVersion, "14.7")
            || verCurrent.Major == 15 && !Utils.IsCurrentMajorMinorVersionNewerOrEqualTo(EngineVersion, "15.2")
            || verCurrent.Major == 16 && !Utils.IsCurrentMajorMinorVersionNewerOrEqualTo(EngineVersion, "16.1"))
            throw new InvalidDataException(error);
    }
}

2024-10-07 06:44 UTC, merged