DUPLO-20758 snapshot_window support in redis (WIP)
duplocloud/terraform-provider-duplocloud pull request #716
Opened 2024-09-25 01:08 UTC by pravin-duplocloud

## Overview

 DUPLO-20758 snapshot_window support in redis
## Summary of changes

This PR does the following:

- snapshot_window support in redis

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- None

2024-09-25 20:59 UTC, ddiaz-duplo reviewed
just adding some suggestions for improving the error messages

2024-09-25 20:59 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected type of %s to be string", k))
```suggestion
			errors = append(errors, fmt.Errorf("the type of '%s' must be a string", k))
```

2024-09-25 20:59 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s in format '05:00-09:00'", k))
```suggestion
			errors = append(errors, fmt.Errorf("the value of '%s' must follow the format 'HH:MM-HH:MM', for example '05:00-09:00'", k))
```

2024-09-25 20:59 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s in format '05:00-09:00'", k))
```suggestion
			errors = append(errors, fmt.Errorf("the value of '%s' must be in the format 'HH:MM-HH:MM', for example '05:00-09:00'", k))
```

2024-09-25 20:59 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s of start-time should be smaller than end-time.", k))
```suggestion
			errors = append(errors, fmt.Errorf("the start time in '%s' must be earlier than the end time", k))
```

2024-09-25 20:59 UTC, zafarabbas commented
Task linked: [DUPLO-20758 [TF] Ability to provide snapshot_window for automated backups](https://app.clickup.com/t/8655600/DUPLO-20758)

2024-10-10 18:48 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected type of %s to be string", k))
done

2024-10-10 18:48 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s in format '05:00-09:00'", k))
done

2024-10-10 18:48 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s in format '05:00-09:00'", k))
done

2024-10-10 18:48 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			errors = append(errors, fmt.Errorf("expected %s of start-time should be smaller than end-time.", k))
done

2024-10-14 06:14 UTC, Duplo-nikv requested changes

2024-10-14 06:14 UTC, Duplo-nikv commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
please mention if endtime is less than startime, endtime is considered to be of next day

2024-10-14 07:01 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
it was intentional ... after 24 hours in midnight
we need to take reminder.

2024-10-14 16:55 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
the diff should be 30 min to 23.30 hour

2024-10-14 17:07 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
Detail:   fmt.Sprintf("The time difference between the start ('%s') and end ('%s') must be at least 30 minutes. For example, '05:00-05:30' is valid, but '05:00-05:20' is not.", times[0], times[1]),

2024-10-15 05:40 UTC, Duplo-nikv commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
I understand the logic, I just meant , add a note in document that if endtime is less than start time , the end time will be the difference carry forward to next day

2024-10-15 06:18 UTC, Duplo-nikv approved these changes
LGTM

2024-11-05 03:16 UTC, pravin-duplocloud commented on duplocloud/resource_duplo_ecache_instance.go
> +			Type:             schema.TypeString,
ok
its implied

2024-12-12 03:30 UTC, Duplo-nikv approved these changes
LGTM

2024-12-12 03:30 UTC, merged