DUPLO-25452: Added support for GCP Redis Instance Resource
duplocloud/terraform-provider-duplocloud pull request #734
Opened 2024-10-17 21:09 UTC by shantanuduplo

## Overview

Added support for GCP Redis Instance Resource.

## Summary of changes

This PR does the following:

- Introduced GCP Redis Instance resource and data sources for managing GCP Redis Instance in DuploCloud.
- Added CRUD operations and data retrieval for GCP Redis Instance resources.

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ] Manually, on a remote test system

2024-10-17 21:09 UTC, zafarabbas commented
Task linked: [DUPLO-25452 Support of google Memorystore (Redis) in duplo tf provider](https://app.clickup.com/t/8655600/DUPLO-25452)

2024-10-18 07:52 UTC, tahir-duplo commented on duplocloud/data_source_duplo_gcp_redis_instance.go
> +			Description:  "The GUID of the tenant that the redis instancels will be created in.",
Typo in the description `instancels`

2024-10-18 07:56 UTC, tahir-duplo commented on duplocloud/data_source_duplo_gcp_redis_instance.go
> +		"name": {
I don't see `fullname` attribute defined in schema

2024-10-18 07:57 UTC, tahir-duplo commented on duplocloud/data_source_duplo_gcp_redis_instance.go
> +	tenantID := d.Get("tenant_id").(string)
We should always retrieve `tenantID` and `name` from ID attribute. Otherwise, import will fail, Please test the import use case as well.

2024-10-18 09:36 UTC, tahir-duplo commented on duplocloud/resource_duplo_gcp_redis_instance.go
> +			Create: schema.DefaultTimeout(3 * time.Minute),
Increase timeout to at least 15 min

2024-10-18 14:01 UTC, Duplo-nikv requested changes

2024-10-18 14:01 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_redis_instance.go
> +		}
try using enum

2024-10-22 05:40 UTC, Duplo-nikv requested changes

2024-10-22 05:40 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_redis_instance.go
> +		return c.RedisInstanceGet(tenantID, name)
duplo.Name

2024-10-23 06:13 UTC, Duplo-nikv approved these changes
LGTM

2024-10-23 08:32 UTC, tahir-duplo approved these changes
LGTM

2024-10-23 08:35 UTC, merged