Shared alb support
duplocloud/terraform-provider-duplocloud pull request #8
Opened 2021-09-17 20:19 UTC by tahir-duplo

- Wait for target groups to be created implementation while ECS service creation.
- Flag based delete implementation for ECS task definition
- Terraform Resource - Add shared load balancer support for ECS.

2021-09-17 22:09 UTC, joek-duplo requested changes

2021-09-17 22:09 UTC, joek-duplo commented on duplocloud/resource_duplo_ecs_service.go
> +			ForceNew:         true,
we should not force a new resource when this flag changes, right?

2021-09-17 22:09 UTC, joek-duplo commented on duplocloud/resource_duplo_ecs_service.go
> +			Optional: true,
is the user even allowed to pass these in?

if not, then only `Computed` should be `true`, and `Optional` should be left as `false`.

2021-09-17 22:09 UTC, joek-duplo commented on duplocloud/resource_duplo_ecs_task_definition.go
> +		"prevent_tf_destroy": {
why should we force the resource to be recreated if this flag changes?

2021-09-17 22:09 UTC, joek-duplo commented on duplocloud/resource_duplo_tenant.go
> +		time.Sleep(time.Duration(45) * time.Second)
ha - thanks.  I've been meaning to do something like this. :)

2021-09-17 22:09 UTC, joek-duplo commented on duplosdk/ecs_task_def.go
> +func (c *Client) EcsTaskDefinitionDelete(tenantID, arn string, preventDestroy bool) ClientError {
we should not have TF concepts in here like `preventDestroy`
move that out into the TF provider code, and out of the SDK code.

2021-09-18 05:12 UTC, tahir-duplo commented on duplocloud/resource_duplo_ecs_service.go
> +			Optional: true,
Done

2021-09-18 05:12 UTC, tahir-duplo commented on duplosdk/ecs_task_def.go
> +func (c *Client) EcsTaskDefinitionDelete(tenantID, arn string, preventDestroy bool) ClientError {
Done

2021-09-18 07:25 UTC, tahir-duplo commented on duplocloud/resource_duplo_ecs_service.go
> +			Optional: true,
I have removed `optional`, which is not required here.

2021-09-18 07:32 UTC, tahir-duplo commented on duplocloud/resource_duplo_ecs_task_definition.go
> +		"prevent_tf_destroy": {
done,

I was facing the following issue without force new, 
Error: InternalValidate
```
Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
        * resource duplocloud_ecs_task_definition: No Update defined, must set
ForceNew on: []string{"prevent_tf_destroy"}
```

I have added an updated context empty implementation to resolve this issue.

2021-09-20 20:25 UTC, joek-duplo approved these changes

2021-09-20 20:25 UTC, merged