DUPLO-26762: remove hardcoded list of database versions. Get them from Duplo API instead
duplocloud/terraform-provider-duplocloud pull request #832
Opened 2024-12-17 00:32 UTC by ddiaz-duplo

## Overview

## Summary of changes

This PR does the following:

- remove hardcoded list of database versions, and versions requiring root passwords. Get them from Duplo API instead

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [x] Manually, on a remote test system

### Tested on gcp-test10
error when trying to create database that requires a root password without a password
![image](https://github.com/user-attachments/assets/cca22ea2-1314-43bf-9fba-6059cd122a6f)

error when using an invalid database version type
![image](https://github.com/user-attachments/assets/42eddcf5-10d3-4549-be27-b746a42a02e5)

## Describe any breaking changes

- ...

2024-12-17 00:32 UTC, zafarabbas commented
Task linked: [DUPLO-26762 Ensure TF plugin works as expected](https://app.clickup.com/t/8655600/DUPLO-26762)

2024-12-20 10:01 UTC, Duplo-nikv requested changes

2024-12-20 10:01 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_sql_database.go
>  		},
change the validateDatabaseVersion to validateFunc format, which will validate the version on terraform plan phase.

2024-12-26 18:12 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_gcp_sql_database.go
>  		},
`ValidateFunc` is meant to stay local and not involve API calls as it may run multiple times within terraform plan. 
It is recommended to keep external calls in the UPDATE/CREATE functions. This is how the google terraform provider is as well https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/sql/resource_sql_database_instance.go#L729

2024-12-26 18:12 UTC, ddiaz-duplo commented on duplocloud/resource_duplo_gcp_sql_database.go
>  	// Post the object to Duplo
`ValidateFunc` is meant to stay local and not involve API calls as it may run multiple times within terraform plan.
It is recommended to keep external calls in the UPDATE/CREATE functions. This is how the google terraform provider is as well https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/sql/resource_sql_database_instance.go#L729

2024-12-30 05:29 UTC, Duplo-nikv approved these changes
LGTM

2024-12-30 05:29 UTC, Duplo-nikv commented on duplocloud/resource_duplo_gcp_sql_database.go
>  	// Post the object to Duplo
ok

2024-12-30 05:29 UTC, merged