Duplo 3732 and DUPLO-3731.
duplocloud/terraform-provider-duplocloud pull request #84
Opened 2022-05-27 08:25 UTC by tahir-duplo

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer.
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-05-27 08:25 UTC, zafarabbas commented
Task linked: [DUPLO-3731 Add azure data source to get storage account keys.](https://app.clickup.com/t/8655600/DUPLO-3731)

2022-05-27 08:25 UTC, zafarabbas commented
Task linked: [DUPLO-3732 Add azure resource for storage_share_file.](https://app.clickup.com/t/8655600/DUPLO-3732)

2022-05-27 13:17 UTC, zafarabbas commented
Task linked: [DUPLO-3731 Add azure data source to get storage account keys.](https://app.clickup.com/t/8655600/DUPLO-3731)

2022-05-27 19:20 UTC, joek-duplo requested changes

2022-05-27 19:20 UTC, joek-duplo commented on duplocloud/resource_duplo_azure_storage_share_file.go
> +
check for `nil` - duplo does not always return a 404

2022-05-28 05:54 UTC, tahir-duplo commented on duplocloud/resource_duplo_azure_storage_share_file.go
> +
Done.

2022-05-30 19:15 UTC, zafarabbas commented
Task linked: [DUPLO-3752 TF: check for nil against all v1 duplo read APIs.](https://app.clickup.com/t/8655600/DUPLO-3752)

2022-06-01 13:48 UTC, joek-duplo approved these changes

2022-06-03 05:30 UTC, merged